version: 2.1
jobs:
  build:
    working_directory: ~/ShowSlowy
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - deploy:
          name: deploy-pages
          command: |
            COMMIT_MSG=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            if [[ $COMMIT_MSG == *"Bump version to"* ]]; then
              git config credential.helper 'cache --timeout=120'
              git config user.email "botcircleci@gmail.com"
              git config user.name "bot-never-sleep"
              git add .
              git commit --allow-empty -m "Trigger deployment"
              # Push quietly to prevent showing the token in log
              git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/withparadox2/ShowSlowly.git master
            fi