name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@0.2
      with:
        args: "https://gitlab.com/withparadox2/slowly"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "withparadox2"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "19621447"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
